### ISSUE TITLE
How do I get the master address and master key right after create the wallet

### ISSUE THREAD

**Issue by vuminhquang** [KZen-networks/gotham-city#23]
Hello KZen people,

First, thank you very much for your cool product 👍 .

Really like multi-parties idea, I wish to try gotham-city as a wallet on testnet.
Currently, I was setup the server and was able to build your client.

After run "./cli create-wallet", got
  (id: 0ce94885-fe95-4d11-b497-85d92f5aae74) Took: PT4.914320007S
  Network: [testnet], Wallet saved to disk

When digging to wallet.data, I found that "master_key" is created.
Please help me that: at this step, **how do I get the master address and master key** (manually)? 
Thank you.

Sincerely,
Quang, VU

**Comment by omershlo** [comment]
Hey, 

I  think that the name "master key" is misleading (cc @oleiba mention this point as well). 
This master key is basically a  root secret share that can be used to generate keys and addresses in a deterministic way.  You should try to generate new address : this will print you the testnet address  to the screen. If you need  also the public key : should be found in the wallet.data file

**Comment by vuminhquang** [comment]
Hi,
Thank you @omershlo , I think that the misleading come from the white-paper
Part 2: A General ThreshSig wallet
  - Distibuted Key Generation (DKG): A multi-party algorithm to generate **a public key** (a blockchain address) and **secret shares** of the private key.

If I understand right, means we only have 1 public key and 1 private key (inform of multiple shares). Could you help me clarify this? 

>>  You should try to generate new address : this will print you the testnet address to the screen
If now I run this 4 times
  "./cli wallet -a"
I will get 4 addresses which are technically equal? And I can get 1 of them to publish outside and start to receive BTC to this?

Thank you very much.

**Comment by omershlo** [comment]
you will get 4 addresses, each one of them is derived deterministically.  you can use each one and publish outside and start to receive TESTNET btc

**Comment by vuminhquang** [comment]
okie, got it. Thank you for clarify @omershlo :)
