### ISSUE TITLE
Cross Compile & Link Gotham Client and GMP for Android Architectures

### ISSUE THREAD

**Issue by jeremyfelder** [KZen-networks/gotham-city#36]
Currently running into the following runtime error when loading .so after compiling GMP and Gotham City and linking in Android:

`java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "SSL_CTX_free" referenced by /lib/arm64/libclient_lib.so`

**Reproduce**

- Running macOS Mojave Kaby Lake
- GMP 6.1.2 source code
- Gotham City source code branch two-party-eddsa with eddsa folder and dependencies removed (with the dependencies Gotham cross compile fails with -lgmp error)
- Added JNI wrapper for KeyGen ECDSA
- Android prebuilt NDKs
- Scripts are run from project root

**Android Folder Structure**
app
|_src
|__main
|___java
|___jniLibs
|____arm64-v8a
|_____libclient_lib.so
|_____libgmp.so

In android app build.gradle I have:
ndk { abiFilters "arm64-v8a" }

In MainActivity.kt I have:
companion object{
      init {
        System.loadLibrary("gmp")
        System.loadLibrary("client_lib")
        }
    }

**Project Folder Structure**
project
|__rust
|___gmp-6.1.2 (source)
|___src (gotham-city/gotham-client source)
build_gmp.sh
build_gotham.sh

**GMP Build Script**
**---------START SCRIPT---------**
out_dir="out"
out_dir_temp="out_temp"
root=$PWD/rust/gmp-6.1.2/

rm -rf ${root}/${out_dir_temp}
mkdir ${root}/${out_dir_temp}
mv  $PWD/rust/gmp-6.1.2/${out_dir}/* $PWD/rust/gmp-6.1.2/${out_dir_temp}/

export BASE_CFLAGS='-O2 -g -pedantic -fomit-frame-pointer -Wa,--noexecstack -ffunction-sections -funwind-tables -no-canonical-prefixes -fno-strict-aliasing'

cd ./rust/gmp-6.1.2/

export LDFLAGS='-Wl,--no-undefined -Wl,-z,noexecstack -Wl,-z,relro -Wl,-z,now'
export CFLAGS="${BASE_CFLAGS} -fstack-protector-strong -finline-limit=300 -funswitch-loops"
export CC="aarch64-linux-android23-clang"
export CXX="aarch64-linux-android23-clang++"

./configure --prefix=/usr --disable-shared --enable-cxx --build=x86_64-pc-linux-gnu --host=aarch64-linux-android MPN_PATH="arm64 generic"
sed -i.bak '/HAVE_LOCALECONV 1/d' ./config.h
make -j8 V=1 2>&1 | tee arm64-v8a.log
mkdir ${out_dir}/aarch64-linux-android
make install DESTDIR=$PWD/${out_dir}/aarch64-linux-android
cd ${out_dir}/aarch64-linux-android && mv usr/lib/* ./ && mv usr/include/* ./  && rm -rf usr 

**---------END SCRIPT---------**

**Gotham Compilation**
**---------START SCRIPT---------**

`root=$PWD`
`cd ./rust`
`export SYSROOT="$toolchain_bin_dir/../sysroot"`
`CC=Library/Android/sdk/ndk/20.0.5594570/toolchains/llvm/prebuilt/darwin-x86_64/bin/aarch64-linux-android23-clang`
`CXX=Library/Android/sdk/ndk/20.0.5594570/toolchains/llvm/prebuilt/darwin-x86_64/bin/aarch64-linux-android23-clang++`
`LDFLAGS=""`
`CFLAGS=""`
`AR=Library/Android/sdk/ndk/20.0.5594570/toolchains/llvm/prebuilt/darwin-x86_64/bin/aarch64-linux-android-ar`
`cargo rustc --target "aarch64-linux-android" --release -- -L ${root}/rust/gmp-6.1.2/out/aarch64-linux-android`

**---------END SCRIPT---------**

**Cargo Config**
[target.aarch64-linux-android]
ar = "$HOME/Library/Android/sdk/ndk/20.0.5594570/toolchains/llvm/prebuilt/darwin-x86_64/bin/aarch64-linux-android-ar"
linker = "$HOME/Library/Android/sdk/ndk/20.0.5594570/toolchains/llvm/prebuilt/darwin-x86_64/bin/aarch64-linux-android23-clang"

**Comment by jeremyfelder** [comment]
Added the EdDSA dependencies back and moved the compiled GMP archive to $SYSROOT/usr/lib/$trgt_platform/$api_num as suggested by @vhnatyk

**Comment by jeremyfelder** [comment]
The original error above was caused by a dependency needing openssl which didn't get packaged together with the .so file. In order to cross compile a dependency that requires openssl you need to compile openssl for the specific target which is (apparently) very difficult. Better to remove the dependency on openssl.

**Comment by vhnatyk** [comment]
👍  Sorry, @jeremyfelder -  $trgt_platform and so on are just var names specific to [my script](https://github.com/vhnatyk/multi-party-ecdsa/blob/dev/android_%2363/gmp_android_build_install.sh)  I would ask you to put exact path. If you got everything working - can the issue be closed? 😊

**Comment by vhnatyk** [comment]
> The original error above was caused by a dependency needing openssl which didn't get packaged together with the .so file. In order to cross compile a dependency that requires openssl you need to compile openssl for the specific target which is (apparently) very difficult. Better to remove the dependency on openssl.

Also - somehow I don't recall building OpenSSL myself) I wouldn't forget if I guess - maybe it's not fluent on Mac or especially Windows, but on Ubuntu, all was pretty good. I just recall having troubles with compiler finding OpenSSL. And that's exactly why 
```
export AARCH64_LINUX_ANDROID_OPENSSL_LIB_DIR=$SYSROOT
export OPENSSL_DIR="/usr/" #depends on your OS and OpenSSL setup
```
are [there](https://github.com/vhnatyk/multi-party-ecdsa/blob/528438033de6588dbb84d9130de21035826c1a0c/android_run.sh#L24) In case you can't sacrifice OpenSSL dependency

**Comment by jeremyfelder** [comment]
Yes, I added `export OPENSSL_DIR="/usr/local/opt/openssl@1.1/"` which caused the original error I had above during runtime.
Adding the `AARCH64_LINUX_ANDROID_OPENSSL_LIB_DIR` var caused some dependencies to fail no matter which openssl path I gave it.
